name: KubithonReplicate
main: org.kubithon.replicate.ReplicatePlugin
version: 0.0.1
authors: [Creart, troopy28]
depend: [LuckPerms]
permissions:
  kubithon.replicate:
    description: Enable a player to be replicated on other servers.
    default: op